### ISSUE TITLE
will there be a video / community standup ?

### ISSUE THREAD

**Issue by Otto404** [davidfowl/Micronetes#15]
I am always impressed by David's "Bastelecke" (his Git repository). But unfortunately I don't have the time (maybe also the knowledge) to deal with interesting projects like Micronetes. After all, I use SignalR productively. :)
I imagine a short video or a community standup about Micronetes would help me a lot. (for Bedrock, FeatherHttp) the same applies. A video to easily pick up simple developers.

**Comment by davidfowl** [comment]
See https://github.com/dotnet/tye for the future of this project. Yes there will be standups!
