### ISSUE TITLE
Build parameter for CLI

### ISSUE THREAD

**Issue by luisgizirian** [davidfowl/Micronetes#18]
Adding a `-build` option to m8s command to initiate building for each `project:` defined service in the .yaml file. This will ease clone-and-fire for many project scenarios when orchestrating with m8s.

(Doesn't look like an immediate requirement)

**Comment by davidfowl** [comment]
Yep! It trips everyone up. I wasn't sure if to make it build by default or not. I also want to integrate watch like features so it would rebuild on a source file change.

**Comment by davidfowl** [comment]
Made it build by default, you can pass --no--build to stop building all projects or set build in the m8s file to stop it from building. The experience will be much better for new comers as well
