### ISSUE TITLE
Is it pronounced "mates" or "em-eights"? Asking for a friend.

### ISSUE THREAD

**Issue by DamianEdwards** [davidfowl/Micronetes#19]
See title

**Comment by DamianEdwards** [comment]
My vote is on "mates" btw.

**Comment by NickCraver** [comment]
I think it's "micro nets", like your own tiny little internet.

**Comment by DamianEdwards** [comment]
My bad, I was referring to the cmd line "m8s". I should have made that clear.

For the long form though, I like @NickCraver's suggestion.

**Comment by NickCraver** [comment]
Maybe that should be "mets"? Like the greatest sports team that ever lived

**Comment by DamianEdwards** [comment]
Sorry, I just don't see how "m8s" == "mets" 🤷‍♂

**Comment by NickCraver** [comment]
Ooooh I missed the rename, alrighty I'm on board with "mates", though it sounds like someone's building a buddy system...possibly for peer reviews.

**Comment by jbogard** [comment]
Not many people know this, the “m” is silent

**Comment by JamesNK** [comment]
Feature request: Rename CLI command to `gdaym8s`

**Comment by jzabroski** [comment]
I can't tell if everyone conspired on Twitter to troll @davidfowl aka BarbadianMachineNeverStopsCoding and see if they can distract him / stop him.

**Comment by analogrelay** [comment]
It’s clearly “mateys”, with a pirate accent

**Comment by PureKrome** [comment]
![](https://media.giphy.com/media/G7Dgk9BQnrVOE/giphy.gif)

**Comment by natemcmaster** [comment]
I think we should address the root cause of Damian's confusion on pronunciation: you have a typo in the project name. It should have been MicroNates.

**Comment by alefranz** [comment]
In Italian, it would read `mottos`

**Comment by theo-albers** [comment]
m8s --> mmmm.mmmm

**Comment by ericwj** [comment]
m88 suffices

**Comment by oising** [comment]
m8s = mates = (mu)chachos  / µchachos

seriously though @davidfowl , never tell anyone how to pronounce it because that's the day this will end up in someone's production environment and all hell will break loose... :D

**Comment by davidfowl** [comment]
See https://github.com/dotnet/tye for the future of this project
