### ISSUE TITLE
Debugging? 

### ISSUE THREAD

**Issue by JohnGalt1717** [davidfowl/Micronetes#2]
This looks super interesting!

How would we go about hooking debuggers etc. to this so we can use say vs code once spun up?

**Comment by davidfowl** [comment]
I would love to get that working, so far if you pass the debug flag it'll wait for you to attach a debugger to all of the processes but it doesn't launch them for you.

**Comment by JohnGalt1717** [comment]
So it opens the ports for the debugger?

**Comment by davidfowl** [comment]
Today no but it will, all progress will be moving to https://github.com/dotnet/tye
