### ISSUE TITLE
Non interactive option for m8s run command

### ISSUE THREAD

**Issue by luisgizirian** [davidfowl/Micronetes#25]
Much like docker-compose, it would be useful for scripting scenarios (where running m8s is one step among others), to make the running non-blocking.

Docker compose has a -d (long form: --detach) for its `up` & `run` commands. Once the initialisation process completes, it goes background.

After checking docker-compose sources (https://github.com/docker/compose), I'm not sure how to implement it in netcore. But still, It would be a nice addition.

Use case: a script that...
* ~~Builds each net core involved project~~ **Update**: m8s now builds by default, so build step(s) not needed (for this scenario at least)
* Initiates a Functions project locally using its Core Tools (which I think would benefit of such a feature itself)
* Runs an `m8s run m8s.yaml` command
* Notifies completion state for a second or two, then finishes.

Sounds reasonable?

**Comment by davidfowl** [comment]
See https://github.com/dotnet/tye for the future of this project
