### ISSUE TITLE
Getting Started doc: consider the lack of a self-signed certificate for SSL on Linux

### ISSUE THREAD

**Issue by luisgizirian** [davidfowl/Micronetes#33]
**Valid for Linux based development**
Those following the step by step on the [Getting Started](https://github.com/davidfowl/Micronetes/blob/master/GettingStarted.md) guide, on Linux, will notice an error at `frontend` web site url hitting time. This is due to the fact that `Startup.cs`, created by dotnet templates, [enforces an HTTPS redirection](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.1&tabs=visual-studio) (for `Production` time, even HSTS is enforced).

As Linux doesn't get an auto self-signed certificate as Windows and MacOS do, it crashes.

Options:
1) Comment these enforcements right after `dotnet new`
2) Haven't tested @andrewlock's proposal yet:
https://andrewlock.net/creating-and-trusting-a-self-signed-certificate-on-linux-for-use-in-kestrel-and-asp-net-core/

Perhaps this is worth mentioning in documentation?

**Comment by davidfowl** [comment]
Ah, it is!

**Comment by davidfowl** [comment]
All progress will be moving to https://github.com/dotnet/tye
