### ISSUE TITLE
Cancel startup

### ISSUE THREAD

**Issue by nj0yeh** [davidfowl/Micronetes#46]
When running multiple `dotnet` processes (which takes a while on a Mac for Microsoft reasons), the startup process takes some time (one minute in my case). When pressing Ctrl+C in the meanwhile, some processes are killed, but processes that are not started yet will continue to start, which slows down the cancellation process. At the end, the result is correct - all processes are quit - but it just takes unnecessary long.

**Comment by davidfowl** [comment]
This [change](https://github.com/davidfowl/Micronetes/commit/bc71daa202117a6b4383a4c2ea7f464575236be3) made process startup and shutdown fully async and it should be a bit faster now as we got some parallelization for free.

**Comment by davidfowl** [comment]
There are still some bugs though

**Comment by nj0yeh** [comment]
We are still on an older version (with our own changes). What are these bugs that you are talking about? Would it be wise to wait before upgrading to the current version?

**Comment by davidfowl** [comment]
@nj0yeh It would be great if you could try it out (as you're my #1 customers 😄 ). There might be issues around:
- Concurrent execution. I haven't hit issues in my testing but they may show up.
- Shutdown. If you cancel the docker start command (during it running) it might leave containers hanging around. This will be solved in a more robust way with this change https://github.com/davidfowl/Micronetes/pull/48

**Comment by nj0yeh** [comment]
On a first look it seems that the startup is correct. My current problem (that is not your fault) is that some of my processes rely on having the Docker processes up. With the new parallel execution of all processes, this is not given. Could be resolved by implementing a dependency chain where we could implement a health check on the MySQL containers that are a prerequisite on other processes.

Total ramp-up time is about the same as before. Perhaps because starting 30 processes at the same time on a 8-core processor is not the best idea.

I cannot test it completely currently because the dependency problem and will go back to the previous version for now.

**Comment by davidfowl** [comment]
I *might* do that anyways as a cheap way to implement dependencies without doing the full thing.

**Comment by davidfowl** [comment]
All progress will be moving to https://github.com/dotnet/tye
