### ISSUE TITLE
Message when startup is finished

### ISSUE THREAD

**Issue by nj0yeh** [davidfowl/Micronetes#47]
Can we please have a message when all processes are started completely (the first time)?

**Comment by davidfowl** [comment]
How would you be using this and what are you doing today without this feature?

**Comment by nj0yeh** [comment]
I want to listen to the output of m8s to detect when I can start firing events to my processes. The current solution is `sleep 120` 😁 .

**Comment by davidfowl** [comment]
> I want to listen to the output of m8s to detect when I can start firing events to my processes. The current solution is sleep 120 😁 .

I don't want you to rely on that. Better to send health checks during a warm up period before sending requests.

**Comment by nj0yeh** [comment]
Of course you are right. I could have thought of that myself.
