### ISSUE TITLE
docker run applications mapping the project output

### ISSUE THREAD

**Issue by davidfowl** [davidfowl/Micronetes#5]
We can run docker on a project and build inside of the container directly. Not sure about cross OS building

**Comment by luisgizirian** [comment]
Just realised that what you're trying to achieve with this effort, brings a huge benefit on battery life savings as well. In doing multi-project on VS for Mac with Docker-Compose, energy burns at a fast rate + heat.

Not sure I'm getting your thought line on this one, but any additional processing inside docker, please make it optional.

**Comment by davidfowl** [comment]
This was based on a suggestion from Twitter. It would be optional for sure as docker does come at a cost.

**Comment by davidfowl** [comment]
See https://github.com/dotnet/tye for the future of this project
