### ISSUE TITLE
Authentication / Windows GMSA support?

### ISSUE THREAD

**Issue by snickler** [davidfowl/Micronetes#50]
I've had a need for [Windows GMSA ](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/gmsa-orchestrate-containers)support and worked with my co-worker early last year to help test it in [K8s](https://kubernetes.io/docs/tasks/configure-pod-container/configure-gmsa/). Would you or others find it useful for m8s to have the ability to pass down some credential spec to the underlying containers?

**Comment by davidfowl** [comment]
What does this look like?

**Comment by davidfowl** [comment]
All progress will be moving to https://github.com/dotnet/tye
