### ISSUE TITLE
Will the project be further developed?

### ISSUE THREAD

**Issue by rakhimzhanov** [davidfowl/Micronetes#54]
Hello team,

I have some questions about the project:
1. Will the project be further developed? (last committed on Jan 25)
2. Do you plan to make some wiki pages? (for newcomers)
3. What can be stored in http://localhost:8001/services/* route? (as I understand it's service information, but what specific information will be there? Currently it's blank)

Thanks

**Comment by davidfowl** [comment]
See https://github.com/dotnet/tye
