### ISSUE TITLE
Unable to run a project service if the executable name differs from the project name

### ISSUE THREAD

**Issue by codeConcussion** [davidfowl/Micronetes#56]
Like most people, we prefix our compiled file names and namespaces with our company name - **OurCompany.Foo.Service.dll**. However, in the file structure we leave off the company name because it's just noise. So we'll have a project named **Foo.Service.csproj** that produces an assembly named **OurCompany.Foo.Service.dll**.

I'm guessing m8s derives the assembly name from the project file name rather than reading the project file to determine what the assembly name should be. The error it gives me is...
**You intended to execute a .NET Core program, but dotnet-Foo\Foo.Service\bin\Debug\netcoreapp3.1\Foo.Service.dll does not exist.**

**Comment by davidfowl** [comment]
Yes this is a good issue to fix. All future development will be done here https://github.com/dotnet/tye BTW. This issue should be fixed once we start using msbuild properly, it's a bit hacky today.

**Comment by davidfowl** [comment]
Fixed here https://github.com/dotnet/tye/issues/184
