### ISSUE TITLE
m8s with Azure functions

### ISSUE THREAD

**Issue by lohithgn** [davidfowl/Micronetes#57]
Question: Can we use m8s to run Azure Functions?
Context: We have a serverless solution that contains around 10 function apps we have. Is it possible to use m8s to run all of them? I tried running - but looks like m8s is trying to do "dotnet run" whereas functions use "func start". M8S would be a great tool for a situation like what we have in our project. Thoughts?

**Comment by luisgizirian** [comment]
@lohithgn, I suggest you move your request to https://github.com/dotnet/tye/issues/18 to gain visibility. Tye is the project where m8s original efforts were moved.
