### ISSUE TITLE
What's the difference with tye?

### ISSUE THREAD

**Issue by jrt324** [davidfowl/Micronetes#58]
I saw the dotnet/tye project and surprised to find out that they both having same features soemthing like local orchestrator .
so , i want  known What's the difference with tye?

**Comment by jkotalik** [comment]
This project was ported to dotnet/tye. Tye is a continuation on Micronetes and another project, Opulence. 

Please use tye instead of Micronetes.

**Comment by suadev** [comment]
@jkotalik so i think this repo need to be archived ?

/cc: @davidfowl

**Comment by davidfowl** [comment]
Yep
