### ISSUE TITLE
Pre net core 3.1 support

### ISSUE THREAD

**Issue by luisgizirian** [davidfowl/Micronetes#7]
A multi-project solution might still coexist 3.1 and earlier .net core versions across projects. Are there plans to support older framework versions? Seen a comment on using MSBuild to support path auto discovery.

Prereq: the corresponding version should be already installed.

**Comment by davidfowl** [comment]
Yep, I was being a bit lazy hard coding that path. I'll make another lazy fix 😄. The temporary workaround is to use the executable directly. I'll be fixing this shortly.

**Comment by davidfowl** [comment]
Latest version should work a bit better here.

**Comment by luisgizirian** [comment]
Thanks David. Closing this one then. :)
