### ISSUE TITLE
How to run an Azure Functions project

### ISSUE THREAD

**Issue by luisgizirian** [davidfowl/Micronetes#8]
Scenarios where Azure Functions (AF) runs as a container (https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-function-linux-custom-image) have a place in Micronetes?

An AF project could be run locally, without dockerizing it, thus accelerating dev loop time. Otherwise, they should be fired separately. I'm focusing on getting everything up and running from a single place.

p.s. nice idea this Micronetes project you've put together :)

**Comment by bradygaster** [comment]
I think this would be a great addition. Maybe not a first priority feature but I like the idea of being able to have a Functions project that the tooling makes it easy to "Kubernetify."

**Comment by luisgizirian** [comment]
Looks like running an Azure Functions project might be achieved by flagging it somehow as such project kind. Then firing it by using the `func start` from the Core Tools.

https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local#start

Optionally, a port can be specified, otherwise the default 7071 kicks in.

**Comment by davidfowl** [comment]
See https://github.com/dotnet/tye for the future of this project
